language: csharp
mono: none
dotnet: 2.1.500
addons:
  sonarcloud:
    organization: "flavio1110-github" # the key of the org you chose at step #3
    token:
      secure: $SONNARCLOUDID
script:
 - dotnet tool install --global dotnet-sonarscanner --version 4.4.2
 - dotnet sonarscanner begin /key:flavio1110_checkout-kata /name:project_name
 - dotnet restore -v Minimal --no-cache
 - dotnet build --configuration Release
 - dotnet test test/CheckoutKata.Mockist.Tests/CheckoutKata.Mockist.Tests.csproj --configuration Release --no-build
 - dotnet test test/CheckoutKata.Classic.Tests/CheckoutKata.Classic.Tests.csproj --configuration Release --no-build
 - dotnet sonarscanner end