
version: 1.0.{build}
image: Visual Studio 2017

before_build:
- dotnet --info
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build
test_script:
- dotnet test test/CheckoutKata.Mockist.Tests/CheckoutKata.Mockist.Tests.csproj
- dotnet test test/CheckoutKata.Classic.Tests/CheckoutKata.Classic.Tests.csproj